package com.ivy2testing;

public class StaticDegreesList {
    
    public static final String[] degree_array = {

            " Degree ",
            " Accounting ",
            " Actuarial Science ",
            " Ancient and Medieval History ",
            " Anthropology ",
            " Applied Science ",
            " Archeology ",
            " Art History ",
            " Astrophysics ",
            " Biochemistry ",
            " Bioinformatics ",
            " Biology ",
            " Biomechanics ",
            " Biomedical Science ",
            " Business Administration ",
            " Business Analytics ",
            " Business Strategy ",
            " Business Technology Management ",
            " Canadian Studies ",
            " Cellular, Molecular, and Microbial Biology ",
            " Chemical Engineering ",
            " Chemistry ",
            " Civil Engineering ",
            " Commerce ",
            " Communication and Media Studies ",
            " Community Rehabilitation ",
            " Computer Science ",
            " Dance ",
            " Dentistry ",
            " Development Studies ",
            " Drama ",
            " Earth Sciences ",
            " East Asian Studies ",
            " Ecology ",
            " Economics ",
            " Education ",
            " Electrical Engineering ",
            " Energy ",
            " English ",
            " Entrepreneurship and Innovation ",
            " Environment ",
            " Film ",
            " Finance ",
            " French ",
            " Geography ",
            " Geology ",
            " Geophysics ",
            " German ",
            " Greek and Roman ",
            " Health ",
            " History ",
            " Indigenous ",
            " International Relations ",
            " Italian ",
            " Kinesiology ",
            " Latin American ",
            " Law ",
            " Law and Society ",
            " Leadership ",
            " Linguistics ",
            " Marketing ",
            " Master\'s Degree ",
            " Math ",
            " Medicine ",
            " Neuroscience ",
            " Nursing ",
            " Philosophy ",
            " Physics ",
            " Physiology ",
            " Political Science ",
            " Psychology ",
            " Plant Biology ",
            " Real Estate ",
            " Religious Studies ",
            " Risk Management and Insurance ",
            " Russian ",
            " Social Work ",
            " Sociology ",
            " Software Engineering ",
            " Spanish ",
            " Urban Studies ",
            " Veterinary Medicine ",
            " Women\'s Studies ",
            " Zoology ",
    };
}
