package com.ivy2testing.util;

public class StaticDegreesList {
    
    public static final String[] degree_array = {

            "Accounting",
            "Actuarial Science",
            "Ancient and Medieval History",
            "Anthropology",
            "Applied Science",
            "Archeology",
            "Architecture",
            "Art History",
            "Astrophysics",
            "Biochemistry",
            "Bioinformatics",
            "Biology",
            "Biomechanics",
            "Biomedical Sciences",
            "Business Administration",
            "Business Analytics",
            "Business Strategy",
            "Business Technology Management",
            "Canadian Studies",
            "Cellular, Molecular, and Microbial Biology",
            "Chemical Engineering",
            "Chemistry",
            "Civil Engineering",
            "Commerce",
            "Communication and Media Studies",
            "Community Rehabilitation",
            "Computer Science",
            "Dance",
            "Dentistry",
            "Development Studies",
            "Drama",
            "Earth Science",
            "East Asian Studies",
            "Ecology",
            "Economics",
            "Education",
            "Electrical Engineering",
            "Energy",
            "English",
            "Entrepreneurship and Innovation",
            "Environmental Design",
            "Environmental Science",
            "Exercise and Health Psychology",
            "Film",
            "Finance",
            "French",
            "Geography",
            "Geology",
            "Geomatics",
            "Geophysics",
            "German",
            "Greek and Roman",
            "Health",
            "History",
            "Human Resources",
            "Indigenous",
            "International Relations",
            "Italian",
            "Kinesiology",
            "Latin American",
            "Law",
            "Law and Society",
            "Leadership",
            "Linguistics",
            "Marketing",
            "Master's Degree",
            "Mathematics",
            "Mechanical Engineering",
            "Medicine",
            "Multidisciplinary Studies",
            "Music",
            "Natural Sciences",
            "Neuroscience",
            "Nursing",
            "Oil and Gas Engineering",
            "Operations Management",
            "PhD",
            "Philosophy",
            "Physics",
            "Physiology",
            "Political Science",
            "Postdoc",
            "Psychology",
            "Planning",
            "Plant Biology",
            "Real Estate",
            "Religious Studies",
            "Risk Management and Insurance",
            "Russian",
            "Social Work",
            "Sociology",
            "Software Engineering",
            "Spanish",
            "Supply Chain Management",
            "Urban Studies",
            "Veterinary Medicine",
            "Visual Studies",
            "Women's Studies",
            "Zoology"
    };
}
